### ISSUE TITLE
mirai适配器成功连接，但似乎接受不到消息

### ISSUE THREAD

**Issue by CoolLoong** [st1020/alicebot#15]
mirai成功接受到消息，测试Bot没有反应输出
test code
```
from alicebot import Plugin
from alicebot.exceptions import GetEventTimeout
from alicebot.log import logger
from alicebot.adapter.mirai.event.base import FriendInfo
from alicebot.typing import T_State
from typing import Type, Union, Generic, TypeVar
from .config import BasePluginConfig, RegexPluginConfig, CommandPluginConfig
T_Config = TypeVar("T_Config", bound=BasePluginConfig)

class TestPlugin(Plugin):
    priority: int = 0
    block: bool = False

    async def handle(self) -> None:
        pass

    async def rule(self) -> bool:
        logger.info(self.event.adapter.name)
        return True

```

config.toml
```
[bot]
plugins = ["chatgpt-qqbot"]
plugin_dirs = ["plugins"]
adapters = ["alicebot.adapter.mirai"]

[bot.log]
verbose_exception = true

[adapter.mirai]
adapter_type = "reverse-ws"
verify_key = "password"
qq = qq
host = "127.0.0.1"
port = 5700
url = "/mirai/ws"
```

setting.yml
```
adapters:
  - reverse-ws
enableVerify: true
verifyKey: password
singleMode: true
adapterSettings:
  reverse-ws:
    destinations:
    - host: 127.0.0.1
      port: 5700
      path: /mirai/ws
      protocol: ws
      method: GET
    reservedSyncId: -1
```
